DROP TABLE IF EXISTS Mods;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Recipes;
DROP TABLE IF EXISTS Ingredients;
DROP TABLE IF EXISTS Languages;
DROP TABLE IF EXISTS Translations;

CREATE TABLE Mods
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name NVARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Items
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  minecraftID NVARCHAR(255) NOT NULL,
  numericalID INTEGER NULL,
  damageValue INTEGER NULL,
  variant NVARCHAR(255) NULL,
  mod INTEGER DEFAULT '1' NOT NULL,
  operationsPerFuel FLOAT NULL,
  silkTouch BOOLEAN DEFAULT 'FALSE' NOT NULL,
  tradeable BOOLEAN DEFAULT 'FALSE' NOT NULL,
  pseudo BOOLEAN DEFAULT 'FALSE' NOT NULL,
  price FLOAT NULL
);

CREATE TABLE Recipes
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  productID INTEGER NOT NULL,
  amount INTEGER NOT NULL
);

CREATE TABLE Ingredients
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  recipeID INTEGER NOT NULL,
  ingredientID INTEGER NOT NULL,
  amount INTEGER NOT NULL
);

CREATE TABLE Languages
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  code NVARCHAR(255) UNIQUE NOT NULL,
  name NVARCHAR(255) NOT NULL
);

CREATE TABLE Translations
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  productID INTEGER NOT NULL,
  languageID INTEGER NOT NULL,
  name NVARCHAR(255) NOT NULL
);